"""Streamlit entry point. Start the app with ``run.ps1``.

Do NOT edit this file to add a feature: features are discovered from ``frontend/features/``.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from frontend.core.app_shell import AppShell  # noqa: E402
from frontend.home.home_page import HomePage  # noqa: E402

AppShell(home_page=HomePage()).run()
